# Generated by Django 2.2.17 on 2021-02-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201109_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='TxId',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
