# Generated by Django 2.2.17 on 2021-02-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210227_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hash',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
    ]
