# Generated by Django 3.2.6 on 2021-08-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_searched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searched',
            name='post',
        ),
        migrations.RemoveField(
            model_name='searched',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='searched',
        ),
    ]
